#!/bin/sh

case "$2" in
  merge|squash) exit 0 ;;
esac

msg_file=$1
first_line=$(head -n1 "$msg_file")

if echo "$first_line" | grep -q "^feat:"; then
  sed -i "1s/^/✨ /" "$msg_file"
elif echo "$first_line" | grep -q "^refactor:"; then
  sed -i "1s/^/♻️ /" "$msg_file"
elif echo "$first_line" | grep -q "^styles:"; then
  sed -i "1s/^/🎨 /" "$msg_file"
elif echo "$first_line" | grep -q "^build:"; then
  sed -i "1s/^/🚧 /" "$msg_file"
fi