project:
  type: website
  output-dir: docs

website:
  description: "Blog pessoal construído com Quarto"
  site-url: https://matheuscasmd.github.io/blog_pessoal/
  title: "Blooogle"
  
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/matheuscasmd
      - icon: linkedin
        href: https://www.linkedin.com/in/matheus-de-castro-5a6593268/
      - icon: steam
        href: https://steamcommunity.com/id/osprett/
format:
  html:
    theme:
      - flatly
    css: styles.css



